#! /bin/bash

xmodmap -e "keycode 31 = i I NoSymbol NoSymbol Up   NoSymbol" 
xmodmap -e "keycode 44 = j J NoSymbol NoSymbol Left   NoSymbol" 
xmodmap -e "keycode 45 = k K NoSymbol NoSymbol Down   NoSymbol" 
xmodmap -e "keycode 46 = l L NoSymbol NoSymbol Right   NoSymbol" 
